In [1]:
import numpy as np

In [2]:
def generate_group(N,m):
    '''parameters:
    N - number of individuals to be distributed
    m - number of groups to be formed
    '''
    x=np.random.permutation(N)+1
    num_member=int(np.ceil(N/m))
    residue = N-num_member
    for i in range(m):
        print('Group %d' %(i+1))
        if i<=i*m:
            print(x[i*num_member:(i+1)*num_member])   
        else:
            print(x[i*num_member:i*num_member+residue])      

In [3]:
generate_group(19,4)

Group 1
[ 5 13 12 11  4]
Group 2
[19 14 17 10  9]
Group 3
[ 2  3 18 16  7]
Group 4
[15  1  6  8]
