In [1]:
import numpy as np

In [2]:
def generate_group(N,m):
    '''parameters:
    N - number of individuals to be distributed
    m - number of groups to be formed
    '''
    x=np.random.permutation(N)+1
    num_member=int(np.ceil(N/m))
    for i in range(m):
        print('Group %d' %(i+1))
        if i<=i*m:
            print(x[i*num_member:(i+1)*num_member])   
        else:
            print(x[i*num_member:N+1])      

In [3]:
generate_group(19,4)

Group 1
[ 2  1 15  5  6]
Group 2
[17 18 14  9  3]
Group 3
[ 8 19 16 11  7]
Group 4
[13 10 12  4]
